# Generated by Django 6.0.3 on 2026-05-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True, help_text='Advice, precautions, diet, rest, review date, etc.'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(blank=True, help_text='Write medicine name, dosage, frequency, and duration.'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='speciality',
            name='icon_emoji',
            field=models.CharField(blank=True, default='✚', help_text='Fallback icon if no image is uploaded.', max_length=20),
        ),
        migrations.AddField(
            model_name='speciality',
            name='show_on_home',
            field=models.BooleanField(default=True, help_text='Show this speciality in Key Specialities on the home page.'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='title',
            field=models.CharField(default='Medical Prescription', max_length=150),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload speciality icon only, for example brain, heart, liver icon. Do not upload doctor photo here.', null=True, upload_to='specialities/'),
        ),
    ]
